services:
  mahjong-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    networks:
      - mahjong-network

networks:
  mahjong-network:
    driver: bridge