name: build

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'backend/**'
      - '.github/workflows/build.yml'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: local
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build all backend packages
        working-directory: backend
        shell: bash
        run: |
          go work sync || true
          go build ./...


