name: lint

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'backend/**'
      - '.github/workflows/lint.yml'

permissions:
  contents: read

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install golangci-lint
        shell: bash
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.3
      - name: Prepare Go workspace
        working-directory: backend
        shell: bash
        run: |
          go work sync || true
      - name: Lint all backend packages
        working-directory: backend
        shell: bash
        run: |
          golangci-lint run --timeout=5m --skip-dirs '(?i)internal/swagger|^gen($|/)' ./...

