name: Swagger Check

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  swagger-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install swagger-cli
        run: npm i -g @apidevtools/swagger-cli

      - name: Validate swagger.yml
        run: swagger-cli validate swagger.yml




